config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :tasks
  root to: 'tasks#index'
  get "/task/:id", to: "tasks#destroy", as: "task_delete"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  enum status: { backlog: 0, in_progress: 1, done: 2 }

  validates :title, presence: true
  validates :status, inclusion: { in: statuses.keys }

  scope :not_done, -> { where.not(status: :done) }

  after_commit :schedule_reminders, on: [:create, :update]

  private

  def schedule_reminders
    TaskReminderJob.set(wait_until: deadline - 1.day).perform_later(self.id) if deadline > 1.day.from_now
    TaskReminderJob.set(wait_until: deadline - 1.hour).perform_later(self.id) if deadline > 1.hour.from_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = current_user.tasks
  end

  def show; end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :status, :deadline)
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(icon_class)
    content_tag(:i, '', class: icon_class)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-YcxBx0nByxQ2iDjKXCfcYXpHFnwhOXZzyGpD5rjiL5jF1tOx7tI5vzRjKdX+jO/YPOIHDssbLfPpzG3qjKL/5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" integrity="sha512-hj16U1GpgHldJjLn6+uzU6gNYTmAFoB7Pr+L6EKmQ1V/4wEeQhWuIBmOkul+Pn4msJN8Yq3xtM1HIceF4t4KjA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://kit.fontawesome.com/4c98592650.js" crossorigin="anonymous"></script>

  
  </head>

  <body style="background-color: beige;">
    <nav class="navbar-expand-lg custom-navbar">
      <div class="container-fluid">
        <%= icon('fa-solid fa-list-check fa-2x') %>
        <div>
          <span>Task Manager</span>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= current_user.email %>
              </li>
              <li class="nav-item">
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= button_to "Sign in", new_user_session_path, class: 'btn' %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: 'btn' %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    

    <div class="container">
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>

      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="card">
  <div class="card-header">
    <h2><%= task.new_record? ? 'New Task' : 'Edit Task' %></h2>
  </div>
  <div class="card-body">
    <%= form_with(model: task, local: true) do |form| %>
      <% if task.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h4 class="alert-heading"><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h4>
          <ul>
            <% task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group mb-3">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :status %>
        <%= form.select :status, Task.statuses.keys.map { |k| [k.humanize, k] }, {}, class: 'form-control' %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :deadline %>
        <%= form.datetime_select :deadline, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path, class: 'btn btn-secondary' %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<%= link_to 'New Task', new_task_path, class: 'btn btn-primary mb-3' %>

<div class="row">
  <% @tasks.each do |task| %>
    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= task.title %></h5>
          <p class="card-text"><%= task.description %></p>
          <p class="card-text"><small class="text-muted">Status: <%= task.status %></small></p>
          <p class="card-text"><small class="text-muted">Deadline: <%= task.deadline %></small></p>
        </div>
        <div class="card-footer text-center">
          <%= link_to edit_task_path(task), class: "btn btn-sm btn-outline-primary" do %>
            <%= icon('fa fa-pen') %> Edit
          <% end %>
          <%= link_to task, class: "btn btn-sm btn-outline-info" do %>
            <%= icon('fa fa-eye') %> Show
          <% end %>
          <%= link_to task_delete_path(task), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" do %>
            <%= icon('fa fa-trash') %> Delete
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path, class: 'btn btn-secondary' %>

app/views/tasks/show.html.erb
<div class="col-md-4 mb-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @task.title %></h5>
      <p class="card-text"><%= @task.description %></p>
      <p class="card-text"><small class="text-muted">Status: <%= @task.status %></small></p>
      <p class="card-text"><small class="text-muted">Deadline: <%= @task.deadline %></small></p>
    </div>
    <div class="card-footer text-center">
      <%= link_to edit_task_path(@task), class: "btn btn-sm btn-outline-primary" do %>
        <%= icon('fa fa-pen') %> Edit
      <% end %>
      <%= link_to task_delete_path(@task), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" do %>
        <%= icon('fa fa-trash') %> Delete
      <% end %>
    </div>
  </div>
</div>